// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxpesWlENAo74bOlgrnknwMIuClPqyGw',
    appId: '1:65389983111:web:893ba102fdebd1b6954f22',
    messagingSenderId: '65389983111',
    projectId: 'clubsys-54907',
    authDomain: 'clubsys-54907.firebaseapp.com',
    storageBucket: 'clubsys-54907.appspot.com',
    measurementId: 'G-EVKMV6V20E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk8eNmtGdupCNn_jOsFL3Pkg1p4DZtsRY',
    appId: '1:65389983111:android:9cef39ad8c0744f6954f22',
    messagingSenderId: '65389983111',
    projectId: 'clubsys-54907',
    storageBucket: 'clubsys-54907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNGeBcXEKmvVtVlhSHt9zR__bVK-nake0',
    appId: '1:65389983111:ios:a93b361457bee574954f22',
    messagingSenderId: '65389983111',
    projectId: 'clubsys-54907',
    storageBucket: 'clubsys-54907.appspot.com',
    iosBundleId: 'com.example.clubSys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNGeBcXEKmvVtVlhSHt9zR__bVK-nake0',
    appId: '1:65389983111:ios:8a83afaefdbeb6b5954f22',
    messagingSenderId: '65389983111',
    projectId: 'clubsys-54907',
    storageBucket: 'clubsys-54907.appspot.com',
    iosBundleId: 'com.example.clubSys.RunnerTests',
  );
}
